name: my_caff
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  http_interceptor: ^2.0.0
  intl: ^0.20.1
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/vectors/
    - assets/animations/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 500
          style: normal
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 700
          style: normal

  uses-material-design: true
